// <auto-generated />
using System;
using EasyRent.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace EasyRent.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200718221729_Seed_Ads")]
    partial class Seed_Ads
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EasyRent.Data.Entities.Ad", b =>
                {
                    b.Property<int>("AdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasColumnType("character varying(500)")
                        .HasMaxLength(500);

                    b.Property<bool>("IsGift")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.Property<int>("MaxDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("AdId");

                    b.ToTable("Ads");

                    b.HasData(
                        new
                        {
                            AdId = 1,
                            Description = "Sit dolores eaque saepe id ducimus saepe. Dolores quia velit voluptate dolores est at debitis dolor dolorum. Dolorem quasi repudiandae quis dolores similique eum. Et tenetur voluptate. Suscipit error dolores eum et fugit recusandae. Quasi est sunt.",
                            IsGift = false,
                            Location = "Gradyton",
                            MaxDays = 4,
                            Price = 58.92m,
                            Title = "Unbranded Steel Mouse"
                        },
                        new
                        {
                            AdId = 2,
                            Description = "Sequi rerum blanditiis ut. Perspiciatis voluptas est voluptate ut et est sed eos. Commodi eos non voluptas dolore similique provident ab reiciendis. Sunt in praesentium est odit vero est animi ducimus sit. Cum natus sequi similique est minima nam. Dolorem modi placeat incidunt voluptatem optio beatae dolores esse.",
                            IsGift = false,
                            Location = "Kianastad",
                            MaxDays = 27,
                            Price = 476.05m,
                            Title = "Incredible Metal Keyboard"
                        },
                        new
                        {
                            AdId = 3,
                            Description = "Ullam fugit voluptatem. Sunt soluta tempora. Ullam est adipisci rerum quis et dolore vel. Laboriosam dolorem adipisci beatae accusantium quisquam ea ipsa. Iste quisquam sed quaerat deleniti nihil quod minima commodi. Sit aspernatur distinctio omnis eaque aut omnis ea.",
                            IsGift = false,
                            Location = "Port Edmouth",
                            MaxDays = 20,
                            Price = 664.10m,
                            Title = "Awesome Plastic Chips"
                        },
                        new
                        {
                            AdId = 4,
                            Description = "Ad qui autem vitae numquam consequuntur quas atque ipsa exercitationem. Eveniet aut quas iste autem facilis soluta et nesciunt. Dolore ea eos. Deserunt quibusdam architecto. Cumque ratione dignissimos quasi ea dicta exercitationem.",
                            IsGift = false,
                            Location = "North Inesview",
                            MaxDays = 16,
                            Price = 528.56m,
                            Title = "Handmade Steel Table"
                        },
                        new
                        {
                            AdId = 5,
                            Description = "Aliquam sunt accusamus repudiandae et. Excepturi at accusantium eaque et. Fuga voluptas et earum nisi voluptatem sit eum et esse.",
                            IsGift = false,
                            Location = "South Lois",
                            MaxDays = 8,
                            Price = 190.88m,
                            Title = "Generic Granite Hat"
                        },
                        new
                        {
                            AdId = 6,
                            Description = "Aspernatur ipsam perspiciatis voluptatibus libero repellendus quos vitae. Quas inventore quaerat sunt ab qui aspernatur. Qui reprehenderit sint. Adipisci fuga quo.",
                            IsGift = false,
                            Location = "Gutkowskiburgh",
                            MaxDays = 13,
                            Price = 173.63m,
                            Title = "Unbranded Plastic Hat"
                        },
                        new
                        {
                            AdId = 7,
                            Description = "Et nemo dolor ducimus ad natus expedita magnam ut ratione. Alias asperiores in quam sunt. Tenetur quia autem in et eligendi nihil. Consequatur et beatae voluptates. Consectetur perspiciatis excepturi laborum amet excepturi voluptatem expedita.",
                            IsGift = false,
                            Location = "Lake Desmond",
                            MaxDays = 26,
                            Price = 926.45m,
                            Title = "Sleek Granite Bacon"
                        },
                        new
                        {
                            AdId = 8,
                            Description = "Repellat vitae commodi ea reprehenderit consequatur eum a. Architecto nostrum et inventore culpa nisi deserunt. Vel corrupti vel reprehenderit et assumenda accusamus facilis nostrum sed. Voluptatibus numquam tempora voluptas inventore quibusdam beatae dolorem.",
                            IsGift = false,
                            Location = "Lake Candace",
                            MaxDays = 5,
                            Price = 233.21m,
                            Title = "Intelligent Fresh Bike"
                        },
                        new
                        {
                            AdId = 9,
                            Description = "Omnis cum cupiditate suscipit occaecati libero. Non ipsam sunt enim quos. Aut magnam libero reiciendis in pariatur delectus nulla. Et sint minima consequuntur distinctio.",
                            IsGift = false,
                            Location = "East Carmine",
                            MaxDays = 1,
                            Price = 526.21m,
                            Title = "Sleek Concrete Hat"
                        },
                        new
                        {
                            AdId = 10,
                            Description = "Facilis optio iste maiores. Deleniti doloribus excepturi qui. Ab saepe natus. Dolores qui qui natus excepturi.",
                            IsGift = false,
                            Location = "North Anastasiabury",
                            MaxDays = 1,
                            Price = 995.41m,
                            Title = "Licensed Wooden Car"
                        },
                        new
                        {
                            AdId = 11,
                            Description = "Deleniti qui consequatur atque sit nihil exercitationem reiciendis quo dolor. Alias praesentium perferendis est ducimus qui et. Magni aut cum alias ut dolor officia. Perspiciatis asperiores aliquid quia voluptates. Fugiat quidem totam dicta beatae et autem aut. Nulla minus nam consequatur animi vel.",
                            IsGift = false,
                            Location = "South Cleora",
                            MaxDays = 8,
                            Price = 566.99m,
                            Title = "Handcrafted Fresh Bacon"
                        },
                        new
                        {
                            AdId = 12,
                            Description = "Corporis maxime in placeat maiores commodi praesentium. Minima fuga autem qui ea molestias voluptatibus. Doloremque eligendi eum enim id quia doloribus molestiae. Dignissimos nesciunt quasi nisi. Tenetur quo aut.",
                            IsGift = false,
                            Location = "Onaville",
                            MaxDays = 12,
                            Price = 353.28m,
                            Title = "Practical Granite Ball"
                        },
                        new
                        {
                            AdId = 13,
                            Description = "Aut consequatur quaerat amet est enim nulla et. Ut enim recusandae magni. Rem id ut sed reprehenderit voluptatem quia tempore ut.",
                            IsGift = false,
                            Location = "Lake Mose",
                            MaxDays = 25,
                            Price = 330.50m,
                            Title = "Handcrafted Concrete Pants"
                        },
                        new
                        {
                            AdId = 14,
                            Description = "Ducimus perferendis et aut quaerat totam et. Dignissimos assumenda et sunt laborum facilis. Et maxime necessitatibus minima aut quibusdam. Ullam laudantium alias quis a totam excepturi. Et fuga enim iure nobis quod omnis est veniam id. Voluptas voluptas et cum est velit dicta.",
                            IsGift = false,
                            Location = "West Toby",
                            MaxDays = 12,
                            Price = 65.88m,
                            Title = "Rustic Soft Sausages"
                        },
                        new
                        {
                            AdId = 15,
                            Description = "Debitis rerum excepturi sit maiores quos. Labore quaerat modi sapiente nobis consequatur voluptatem est perspiciatis. Aperiam facere qui temporibus ipsam. Accusamus sunt aut voluptatem. Natus adipisci rerum possimus accusantium explicabo nulla.",
                            IsGift = false,
                            Location = "East Desmond",
                            MaxDays = 24,
                            Price = 275.82m,
                            Title = "Small Cotton Table"
                        },
                        new
                        {
                            AdId = 16,
                            Description = "Eligendi ipsa et voluptas. Dolorem porro quia ipsam libero error quo. Et aut totam exercitationem soluta veritatis qui quia. Ad dolor numquam voluptatem aperiam magnam deleniti laboriosam. Rerum velit quod qui veritatis. Repellendus eaque quis.",
                            IsGift = false,
                            Location = "McClurechester",
                            MaxDays = 13,
                            Price = 283.37m,
                            Title = "Handcrafted Rubber Chair"
                        },
                        new
                        {
                            AdId = 17,
                            Description = "Voluptas facere consequatur reprehenderit et eaque assumenda qui omnis. Temporibus laudantium optio reiciendis. Cum sint ut nulla illum. Molestias rerum eligendi expedita fuga. Pariatur saepe provident minus sit aliquid tempore in animi occaecati. Illum ea nostrum eum ut fugiat culpa laudantium aut.",
                            IsGift = false,
                            Location = "Berniecestad",
                            MaxDays = 6,
                            Price = 683.80m,
                            Title = "Rustic Steel Table"
                        },
                        new
                        {
                            AdId = 18,
                            Description = "Tempore id ullam. Et quo sit. Est aut accusantium ea porro nesciunt. Vitae corrupti cupiditate ut enim consequatur fugit consectetur.",
                            IsGift = false,
                            Location = "Coymouth",
                            MaxDays = 9,
                            Price = 364.92m,
                            Title = "Small Fresh Ball"
                        },
                        new
                        {
                            AdId = 19,
                            Description = "Atque nulla et occaecati ut. Unde eius commodi aut ex. Sit qui ducimus blanditiis animi nobis iste deleniti voluptatibus.",
                            IsGift = false,
                            Location = "South Karlee",
                            MaxDays = 17,
                            Price = 880.44m,
                            Title = "Intelligent Rubber Tuna"
                        },
                        new
                        {
                            AdId = 20,
                            Description = "Quo aut vitae incidunt enim facilis error eius sequi nihil. Dignissimos nemo quo. Aut nisi quo voluptates ducimus neque porro quod suscipit dolor. Cupiditate delectus iure amet repellat.",
                            IsGift = false,
                            Location = "Troyhaven",
                            MaxDays = 16,
                            Price = 53.66m,
                            Title = "Gorgeous Wooden Keyboard"
                        },
                        new
                        {
                            AdId = 21,
                            Description = "Laudantium ea inventore. Eos aliquam impedit tempore repellat voluptas impedit maxime aut omnis. Et maxime ab. Quia mollitia fugiat. Nihil quos quas nihil quia fugiat quidem dolor cumque explicabo. Optio enim soluta voluptate voluptatem doloremque.",
                            IsGift = false,
                            Location = "Greenholtbury",
                            MaxDays = 11,
                            Price = 289.08m,
                            Title = "Licensed Frozen Computer"
                        },
                        new
                        {
                            AdId = 22,
                            Description = "Et fugit aut eligendi odio harum iusto harum iusto ea. Iure quo commodi nam aut et error veritatis consequatur. Laboriosam minus asperiores nemo corporis ducimus. Dolores cum sed corporis non nulla dolores.",
                            IsGift = false,
                            Location = "New Guillermoshire",
                            MaxDays = 3,
                            Price = 876.05m,
                            Title = "Small Frozen Chips"
                        },
                        new
                        {
                            AdId = 23,
                            Description = "Blanditiis accusantium nobis minima neque ea. Qui id neque. Fugit eum dolores amet illum dolores.",
                            IsGift = false,
                            Location = "Shanahanport",
                            MaxDays = 14,
                            Price = 995.16m,
                            Title = "Intelligent Rubber Table"
                        },
                        new
                        {
                            AdId = 24,
                            Description = "Repellat recusandae sit consequatur est autem debitis. Nihil recusandae vero excepturi magni dolore nisi labore aut. Voluptatum sit fugiat aut inventore omnis numquam dolores.",
                            IsGift = false,
                            Location = "Wardview",
                            MaxDays = 24,
                            Price = 85.63m,
                            Title = "Refined Frozen Bacon"
                        },
                        new
                        {
                            AdId = 25,
                            Description = "Enim quibusdam est quia molestias quis voluptas aut. Dolore optio minima fugit possimus quaerat sint rerum. Possimus fugit debitis dolor.",
                            IsGift = false,
                            Location = "New Bettyeside",
                            MaxDays = 12,
                            Price = 626.96m,
                            Title = "Refined Steel Soap"
                        },
                        new
                        {
                            AdId = 26,
                            Description = "Optio delectus quia architecto. Excepturi unde sed quia. Delectus odio qui eos nihil sed ipsum voluptates est illo. Est quos facilis ut quia id saepe dolores aperiam quidem.",
                            IsGift = false,
                            Location = "Generalton",
                            MaxDays = 13,
                            Price = 788.93m,
                            Title = "Ergonomic Fresh Bacon"
                        },
                        new
                        {
                            AdId = 27,
                            Description = "Asperiores cumque et amet. Quisquam quae est sunt. Sunt voluptates voluptatem ut et voluptatum provident odit. Et expedita voluptatibus qui ad voluptatem inventore ullam dignissimos repudiandae. Voluptas fugit ut nulla tenetur quasi.",
                            IsGift = false,
                            Location = "Jadamouth",
                            MaxDays = 15,
                            Price = 559.37m,
                            Title = "Intelligent Steel Pants"
                        },
                        new
                        {
                            AdId = 28,
                            Description = "Fugit eos dolores enim unde minus pariatur consequatur. Perferendis natus officia et qui quam id. Harum aliquid aut itaque quam veniam pariatur pariatur architecto. Praesentium ut qui recusandae temporibus. In earum iusto rerum animi voluptates mollitia ut.",
                            IsGift = false,
                            Location = "West Tristonport",
                            MaxDays = 2,
                            Price = 591.12m,
                            Title = "Generic Steel Sausages"
                        },
                        new
                        {
                            AdId = 29,
                            Description = "Repellat sunt aut optio culpa facilis. Voluptatum reprehenderit iure laudantium aut beatae. Eos nostrum velit voluptatibus expedita quia est possimus impedit. Magni laboriosam laboriosam illum atque quo reprehenderit reprehenderit voluptatem.",
                            IsGift = false,
                            Location = "Paulland",
                            MaxDays = 24,
                            Price = 247.10m,
                            Title = "Refined Plastic Keyboard"
                        },
                        new
                        {
                            AdId = 30,
                            Description = "Debitis optio amet eos. Quia ullam molestiae vitae ullam aliquam eligendi et. Doloremque similique et corporis est doloribus soluta asperiores quasi. Natus voluptatibus nihil.",
                            IsGift = false,
                            Location = "Vallieland",
                            MaxDays = 11,
                            Price = 36.17m,
                            Title = "Gorgeous Rubber Bacon"
                        },
                        new
                        {
                            AdId = 31,
                            Description = "Voluptatum animi rerum sit veniam enim sunt voluptas dolorem unde. Quod soluta et repellat quos. Cupiditate aut fuga aut corporis possimus.",
                            IsGift = false,
                            Location = "Lake Jason",
                            MaxDays = 29,
                            Price = 944.50m,
                            Title = "Intelligent Cotton Chicken"
                        },
                        new
                        {
                            AdId = 32,
                            Description = "Fuga voluptas cumque consequatur aut qui nobis reiciendis voluptatem minus. Voluptate omnis enim excepturi ea perspiciatis. Doloremque hic qui voluptas quia voluptas quia ea aut.",
                            IsGift = false,
                            Location = "East Karina",
                            MaxDays = 13,
                            Price = 862.08m,
                            Title = "Gorgeous Soft Car"
                        },
                        new
                        {
                            AdId = 33,
                            Description = "Corrupti quidem consequuntur velit est. Similique voluptas inventore alias quia dignissimos officia cum iste. Beatae dolores dolor officia eos fugiat in officia. Eum est enim similique qui. Numquam distinctio veritatis inventore quia et facere aut inventore id. Fugit ea animi voluptates natus et et.",
                            IsGift = false,
                            Location = "East Elianeburgh",
                            MaxDays = 8,
                            Price = 434.98m,
                            Title = "Handcrafted Concrete Hat"
                        },
                        new
                        {
                            AdId = 34,
                            Description = "Aut quaerat omnis sint sit doloribus dolor cupiditate dolorum. Facere voluptas est quisquam maiores. Quisquam repellat maiores quam enim. Dignissimos commodi a nobis earum in et ea ut commodi. Doloribus ab nisi possimus adipisci iure laborum magni eaque dolore. Blanditiis vero est omnis ad sunt recusandae.",
                            IsGift = false,
                            Location = "South Irmamouth",
                            MaxDays = 4,
                            Price = 814.26m,
                            Title = "Fantastic Frozen Gloves"
                        },
                        new
                        {
                            AdId = 35,
                            Description = "Saepe numquam vel iure odio optio. Rerum deserunt cupiditate est autem nostrum incidunt distinctio. Et aspernatur beatae iure consequuntur ut totam qui vel dignissimos.",
                            IsGift = false,
                            Location = "Port Justine",
                            MaxDays = 11,
                            Price = 238.17m,
                            Title = "Small Rubber Fish"
                        },
                        new
                        {
                            AdId = 36,
                            Description = "Dolores quasi esse. Debitis quidem et velit harum dolor voluptatem ipsam dignissimos rerum. Vero aliquam expedita aliquam ex maxime.",
                            IsGift = false,
                            Location = "Kiarashire",
                            MaxDays = 8,
                            Price = 728.97m,
                            Title = "Ergonomic Concrete Ball"
                        },
                        new
                        {
                            AdId = 37,
                            Description = "Perspiciatis dicta et autem quo nobis neque excepturi quos. Inventore aspernatur quidem. Magni quas facilis accusamus vel. Et quos temporibus veniam atque dolores quam distinctio voluptatem. Ut quia architecto consequatur id tempora vel.",
                            IsGift = false,
                            Location = "New Chanelton",
                            MaxDays = 5,
                            Price = 766.06m,
                            Title = "Incredible Metal Towels"
                        },
                        new
                        {
                            AdId = 38,
                            Description = "Quia tempora laudantium commodi et facere et illo. Nisi enim laboriosam voluptatem quas. Delectus omnis recusandae voluptatem ut. Et est iste numquam sed quo possimus est. Mollitia non natus quo sed molestiae. Ut eius quia.",
                            IsGift = false,
                            Location = "South Timmothy",
                            MaxDays = 15,
                            Price = 780.83m,
                            Title = "Incredible Frozen Soap"
                        },
                        new
                        {
                            AdId = 39,
                            Description = "Sed facere provident libero voluptatem eius sed voluptates ratione. Ipsa ratione voluptas qui placeat vel dolor omnis. Odio et officiis porro optio aut magni reiciendis eius est. Nostrum consequuntur aut molestiae earum voluptas qui saepe est voluptatem. Voluptatem possimus sint veniam ipsam modi. Quisquam in provident.",
                            IsGift = false,
                            Location = "New Ezra",
                            MaxDays = 27,
                            Price = 663.72m,
                            Title = "Small Fresh Pizza"
                        },
                        new
                        {
                            AdId = 40,
                            Description = "Ipsam dolores et velit. Ipsum ea aut et maiores necessitatibus eos est ab facere. Sed esse corrupti. Accusamus et autem quis recusandae molestias et accusantium minima aut. Doloremque et beatae architecto sit excepturi aut. Ratione qui tempora vel esse.",
                            IsGift = false,
                            Location = "Jettshire",
                            MaxDays = 9,
                            Price = 146.81m,
                            Title = "Awesome Fresh Shirt"
                        },
                        new
                        {
                            AdId = 41,
                            Description = "Quis vel omnis officiis deleniti ea perspiciatis autem id aut. Vero inventore sunt aut minus est. Ab nisi dicta. Nobis sapiente qui et perspiciatis sit aut minus.",
                            IsGift = false,
                            Location = "Corkeryfurt",
                            MaxDays = 25,
                            Price = 707.14m,
                            Title = "Gorgeous Concrete Tuna"
                        },
                        new
                        {
                            AdId = 42,
                            Description = "Id dignissimos dolorum quo asperiores repellendus odio qui voluptatem velit. Id consequatur doloremque saepe est magni et qui quae eos. Quos accusamus dolores ad. Et et porro voluptatum. Rem sunt quod rerum voluptatem aut delectus earum doloribus ratione.",
                            IsGift = false,
                            Location = "South Pearlieberg",
                            MaxDays = 24,
                            Price = 627.42m,
                            Title = "Unbranded Frozen Keyboard"
                        },
                        new
                        {
                            AdId = 43,
                            Description = "Culpa aspernatur reprehenderit hic placeat in. Qui velit non id itaque aut ut ad. Aliquam cumque sequi fugiat velit. Quo velit accusantium.",
                            IsGift = false,
                            Location = "Port Jerelmouth",
                            MaxDays = 10,
                            Price = 883.59m,
                            Title = "Awesome Steel Shoes"
                        },
                        new
                        {
                            AdId = 44,
                            Description = "Ut est ad qui dolore ea autem dolorum voluptate provident. Delectus quas suscipit libero veniam reiciendis fuga exercitationem cupiditate. Adipisci molestiae tempore tempore tempora aut. Facilis voluptatem et et quis veniam rerum error molestiae possimus. Voluptas voluptatem explicabo temporibus dolores quaerat itaque. Labore est animi est reprehenderit quia quis est voluptatem voluptas.",
                            IsGift = false,
                            Location = "Mitcheltown",
                            MaxDays = 11,
                            Price = 913.02m,
                            Title = "Tasty Cotton Soap"
                        },
                        new
                        {
                            AdId = 45,
                            Description = "Modi reprehenderit odit at eius eaque blanditiis. Nostrum ea et esse id. Est incidunt ipsa esse. Voluptas alias cum autem quibusdam dolorem aperiam.",
                            IsGift = false,
                            Location = "Jenningsborough",
                            MaxDays = 4,
                            Price = 405.07m,
                            Title = "Unbranded Frozen Pants"
                        },
                        new
                        {
                            AdId = 46,
                            Description = "Perspiciatis placeat iure aliquid quisquam aut ipsam maxime sit. Maiores dolor in nobis. Ut architecto asperiores officia perspiciatis mollitia nemo doloremque amet rem. Voluptates ipsum alias perspiciatis voluptatum reprehenderit rem molestiae est exercitationem. Sit est saepe. Ab totam quidem quae repellendus.",
                            IsGift = false,
                            Location = "Ornville",
                            MaxDays = 13,
                            Price = 813.38m,
                            Title = "Tasty Soft Bike"
                        },
                        new
                        {
                            AdId = 47,
                            Description = "Quisquam velit debitis facere. Qui maxime temporibus quo. Enim et asperiores quidem earum necessitatibus iure.",
                            IsGift = false,
                            Location = "Cheyannemouth",
                            MaxDays = 26,
                            Price = 390.40m,
                            Title = "Rustic Metal Car"
                        },
                        new
                        {
                            AdId = 48,
                            Description = "Similique minus provident quidem magnam cum qui in eum nemo. Eligendi eius corporis soluta molestiae ducimus rem quaerat tempore. Quos et iste inventore ipsa cumque reprehenderit.",
                            IsGift = false,
                            Location = "North Christy",
                            MaxDays = 22,
                            Price = 960.28m,
                            Title = "Rustic Wooden Car"
                        },
                        new
                        {
                            AdId = 49,
                            Description = "Veritatis reiciendis perspiciatis veritatis aut qui sed consequatur sapiente et. Laudantium eligendi eius temporibus. Et beatae consequatur aut in quia aut.",
                            IsGift = false,
                            Location = "East Oraland",
                            MaxDays = 5,
                            Price = 731.20m,
                            Title = "Small Wooden Soap"
                        },
                        new
                        {
                            AdId = 50,
                            Description = "Velit veniam magni quos vel suscipit. Illo beatae praesentium. Accusamus commodi ut repudiandae. Qui aspernatur dolore sed eum at. Atque illum suscipit.",
                            IsGift = false,
                            Location = "West Dortha",
                            MaxDays = 28,
                            Price = 118.47m,
                            Title = "Awesome Metal Mouse"
                        },
                        new
                        {
                            AdId = 51,
                            Description = "Odio earum cumque rem tenetur cupiditate magni. Eum vel esse voluptatem ut laboriosam voluptas. Autem perspiciatis aut. Minima facilis cum ipsa officiis quidem omnis. Laboriosam eligendi sequi sequi. Ea hic temporibus in.",
                            IsGift = false,
                            Location = "Fritschhaven",
                            MaxDays = 22,
                            Price = 490.73m,
                            Title = "Handcrafted Cotton Sausages"
                        },
                        new
                        {
                            AdId = 52,
                            Description = "Recusandae in sunt neque. Aut dolore incidunt autem. Expedita animi voluptatem placeat a. Dolores modi quaerat maiores.",
                            IsGift = false,
                            Location = "Howellmouth",
                            MaxDays = 19,
                            Price = 603.52m,
                            Title = "Incredible Concrete Pizza"
                        },
                        new
                        {
                            AdId = 53,
                            Description = "Labore sed natus atque voluptas mollitia magnam provident maiores ab. Quia nesciunt cupiditate maxime quia recusandae fugit voluptas ipsam occaecati. Nam voluptas voluptatem unde. Totam natus officiis. Voluptate odio et accusantium sed ipsa fugiat et commodi. Id labore quia quasi expedita incidunt perferendis aut molestiae ea.",
                            IsGift = false,
                            Location = "North Janisview",
                            MaxDays = 1,
                            Price = 456.24m,
                            Title = "Intelligent Wooden Gloves"
                        },
                        new
                        {
                            AdId = 54,
                            Description = "Ut aut consectetur molestias minus ex dolores quia magni. Quia ea reprehenderit. Reiciendis praesentium aliquam distinctio ipsam voluptatem qui magni excepturi qui. Ut sit consequatur vitae consequatur. Est aut qui harum consequuntur perferendis natus molestiae.",
                            IsGift = false,
                            Location = "Leannonfurt",
                            MaxDays = 9,
                            Price = 263.35m,
                            Title = "Unbranded Metal Car"
                        },
                        new
                        {
                            AdId = 55,
                            Description = "Repellat reiciendis quas. Sed velit voluptas animi praesentium ipsum omnis accusantium quos consequuntur. Molestiae mollitia animi magnam minima. Dignissimos eligendi id odio quas voluptates fugiat magnam consequatur. Saepe assumenda sapiente vitae fugiat dolorem harum enim.",
                            IsGift = false,
                            Location = "Schillermouth",
                            MaxDays = 17,
                            Price = 392.92m,
                            Title = "Rustic Fresh Chair"
                        },
                        new
                        {
                            AdId = 56,
                            Description = "Fugiat voluptas et dolorem veniam adipisci iste veniam voluptas ut. Quis aut ut. Dolores accusamus aliquam provident ipsa quos voluptatem delectus. Nemo corrupti quia necessitatibus corporis. Officia rem commodi vero esse atque id.",
                            IsGift = false,
                            Location = "South Nyasiamouth",
                            MaxDays = 17,
                            Price = 404.63m,
                            Title = "Ergonomic Concrete Tuna"
                        },
                        new
                        {
                            AdId = 57,
                            Description = "Ut saepe nostrum mollitia. Quas atque sunt ea id sint. Accusamus nam voluptatibus amet hic iste et sequi recusandae. Necessitatibus aut assumenda voluptas. Earum vero officiis sunt et nihil ratione. Voluptate quis doloribus aut vero autem nulla quia et unde.",
                            IsGift = false,
                            Location = "Stanleyhaven",
                            MaxDays = 17,
                            Price = 218.59m,
                            Title = "Rustic Metal Fish"
                        },
                        new
                        {
                            AdId = 58,
                            Description = "Minus alias atque eum. Asperiores ut porro atque est et sunt quisquam. In eveniet a qui veritatis dolor dicta quae. Aliquam architecto et. Vel rerum minus voluptate sint beatae ut aliquam.",
                            IsGift = false,
                            Location = "Lake Carrie",
                            MaxDays = 8,
                            Price = 866.00m,
                            Title = "Refined Wooden Tuna"
                        },
                        new
                        {
                            AdId = 59,
                            Description = "Id dolor amet doloribus voluptatem dolor aspernatur tempore. Nesciunt nobis reiciendis incidunt facere accusamus nisi neque architecto. Labore hic aut qui nihil quia explicabo quibusdam.",
                            IsGift = false,
                            Location = "East Tyrese",
                            MaxDays = 29,
                            Price = 408.75m,
                            Title = "Licensed Rubber Shoes"
                        },
                        new
                        {
                            AdId = 60,
                            Description = "Iure voluptatem omnis enim dolore incidunt. Sunt nihil sunt voluptate quis cupiditate tempore illo. Reiciendis id deserunt ea omnis vel modi eum possimus rem. Velit ad ipsum distinctio veniam sit debitis est facere adipisci. Cumque dolor architecto pariatur facere cupiditate iure ut cum ad.",
                            IsGift = false,
                            Location = "Leannonfort",
                            MaxDays = 25,
                            Price = 880.40m,
                            Title = "Incredible Metal Towels"
                        },
                        new
                        {
                            AdId = 61,
                            Description = "Iste est voluptas perspiciatis. Magnam repudiandae consequuntur amet facilis. Ullam eligendi ab aperiam vel veniam voluptates veritatis optio asperiores.",
                            IsGift = false,
                            Location = "Schmelerstad",
                            MaxDays = 9,
                            Price = 757.39m,
                            Title = "Incredible Fresh Shirt"
                        },
                        new
                        {
                            AdId = 62,
                            Description = "Velit expedita accusantium quis. Qui provident iste et laborum voluptatem repellendus doloremque autem id. Omnis quibusdam et quae temporibus excepturi in dolor est. Cumque dolore ut et vitae est suscipit totam optio rerum. Cum aut commodi placeat ex natus dicta minus. Assumenda aliquam est.",
                            IsGift = false,
                            Location = "Manntown",
                            MaxDays = 11,
                            Price = 806.90m,
                            Title = "Fantastic Metal Ball"
                        },
                        new
                        {
                            AdId = 63,
                            Description = "A placeat veniam sit mollitia non sed. Error cum sapiente sequi aut eligendi. Ullam iusto hic enim dignissimos est quia ducimus. Est laboriosam illo reprehenderit non vitae aut. Qui beatae ratione laborum laudantium laboriosam. Iste adipisci omnis sed in qui omnis laudantium suscipit et.",
                            IsGift = false,
                            Location = "Vancemouth",
                            MaxDays = 29,
                            Price = 402.75m,
                            Title = "Refined Soft Gloves"
                        },
                        new
                        {
                            AdId = 64,
                            Description = "Aliquam voluptatum ratione et deleniti nam. Suscipit voluptatem unde explicabo fugiat explicabo voluptatibus. Magnam modi alias accusamus eum eum debitis porro omnis. Magni enim iusto. Magnam qui nemo id non quo.",
                            IsGift = false,
                            Location = "North Londonchester",
                            MaxDays = 28,
                            Price = 148.29m,
                            Title = "Practical Cotton Cheese"
                        },
                        new
                        {
                            AdId = 65,
                            Description = "Vero possimus consectetur voluptatem id placeat et eveniet. Vel possimus eum ut aliquid qui qui. Assumenda voluptatem repellendus explicabo neque enim tempore sed deserunt minima. Soluta iure et non tempora nisi enim sint dolore ut. Est debitis quo aliquid suscipit voluptas nam qui.",
                            IsGift = false,
                            Location = "South Abigale",
                            MaxDays = 16,
                            Price = 671.77m,
                            Title = "Generic Soft Towels"
                        },
                        new
                        {
                            AdId = 66,
                            Description = "Occaecati rerum perferendis totam rem numquam. Rerum dolorem sequi natus. Aut eveniet est. Quas et quaerat. Recusandae ut sed eos voluptates ducimus cum eos omnis.",
                            IsGift = false,
                            Location = "South Nona",
                            MaxDays = 18,
                            Price = 28.90m,
                            Title = "Handmade Plastic Tuna"
                        },
                        new
                        {
                            AdId = 67,
                            Description = "Fuga neque reprehenderit et molestias ipsum. Harum aut debitis unde dolores. Quia rerum omnis ipsum velit sequi natus accusantium ut.",
                            IsGift = false,
                            Location = "East Kaden",
                            MaxDays = 21,
                            Price = 797.26m,
                            Title = "Sleek Fresh Mouse"
                        },
                        new
                        {
                            AdId = 68,
                            Description = "Voluptas quas quidem est perspiciatis nulla. Eligendi dolorum vel. Voluptatibus numquam nesciunt et odio est voluptatum. Voluptates voluptatum et vel vitae fugiat quia.",
                            IsGift = false,
                            Location = "Shieldsbury",
                            MaxDays = 24,
                            Price = 780.94m,
                            Title = "Tasty Rubber Car"
                        },
                        new
                        {
                            AdId = 69,
                            Description = "Est ut consequatur voluptas eum. Earum non ut nisi delectus autem. Ea illum autem. Esse perferendis impedit quia omnis illum laboriosam. Velit voluptatem quo aperiam fuga et neque aliquid quis facere. Rem incidunt non perferendis cum dolorem.",
                            IsGift = false,
                            Location = "South Dayanastad",
                            MaxDays = 24,
                            Price = 16.11m,
                            Title = "Tasty Cotton Gloves"
                        },
                        new
                        {
                            AdId = 70,
                            Description = "Aspernatur eius eos. Nam ducimus sit qui odit dolor. Repudiandae aut accusantium voluptas id.",
                            IsGift = false,
                            Location = "Port Geoffrey",
                            MaxDays = 27,
                            Price = 1.52m,
                            Title = "Small Frozen Table"
                        },
                        new
                        {
                            AdId = 71,
                            Description = "Nostrum molestiae corporis. Et exercitationem exercitationem quia magnam et laborum eaque aut. Ut officiis similique doloribus assumenda sunt iusto error aut. Id et hic dolore eaque et.",
                            IsGift = false,
                            Location = "New Arvilla",
                            MaxDays = 18,
                            Price = 157.06m,
                            Title = "Handmade Fresh Bike"
                        },
                        new
                        {
                            AdId = 72,
                            Description = "Dolorum soluta est. Asperiores quia aspernatur mollitia perspiciatis magni laudantium delectus. Possimus nam est esse saepe voluptatem consequuntur nisi. Dicta amet et. Tenetur ut et officia doloremque sit iusto porro tenetur facere.",
                            IsGift = false,
                            Location = "Hagenesbury",
                            MaxDays = 9,
                            Price = 401.77m,
                            Title = "Fantastic Metal Salad"
                        },
                        new
                        {
                            AdId = 73,
                            Description = "Aperiam voluptas et et laboriosam. Aut nihil impedit sunt mollitia officia eveniet vitae quis eos. Tenetur aspernatur magni non hic aut voluptates recusandae odit deleniti. Est doloribus nisi dolor qui et debitis fuga sit adipisci. Dicta ea perferendis aut eum.",
                            IsGift = false,
                            Location = "East Hallieborough",
                            MaxDays = 28,
                            Price = 539.13m,
                            Title = "Fantastic Soft Bacon"
                        },
                        new
                        {
                            AdId = 74,
                            Description = "Vitae cupiditate repellat et incidunt totam asperiores optio porro. Esse alias in sed. Provident est nihil aut assumenda sint earum quam. Qui optio qui et amet id deserunt consequatur.",
                            IsGift = false,
                            Location = "Lake Peterton",
                            MaxDays = 11,
                            Price = 697.33m,
                            Title = "Small Rubber Pants"
                        },
                        new
                        {
                            AdId = 75,
                            Description = "Sequi quod sed perferendis dolores. Consequatur est quae et. Quaerat qui aut dolore est provident quia molestiae. Fugit harum ab necessitatibus tempore ea facilis.",
                            IsGift = false,
                            Location = "North Marisolbury",
                            MaxDays = 13,
                            Price = 201.01m,
                            Title = "Handcrafted Concrete Chair"
                        },
                        new
                        {
                            AdId = 76,
                            Description = "Aut eveniet dolor repellat unde error velit totam. Repellat sunt molestiae corrupti ullam dignissimos aut dolor. Eligendi ipsam nisi qui non consequatur provident. Esse ullam inventore quos fugiat. Dolore nulla enim doloremque.",
                            IsGift = false,
                            Location = "North Ashley",
                            MaxDays = 15,
                            Price = 477.55m,
                            Title = "Intelligent Soft Tuna"
                        },
                        new
                        {
                            AdId = 77,
                            Description = "Adipisci sunt sapiente qui. Placeat ipsam non nisi veniam quis. Totam sit voluptatem fugit velit.",
                            IsGift = false,
                            Location = "East Rosinafurt",
                            MaxDays = 20,
                            Price = 985.69m,
                            Title = "Practical Granite Car"
                        },
                        new
                        {
                            AdId = 78,
                            Description = "Quo eos reiciendis aut. Vel ipsum quia laboriosam distinctio sit dicta et. Quas doloremque expedita. Est et laboriosam commodi temporibus officia deleniti quaerat rem omnis.",
                            IsGift = false,
                            Location = "South Theresebury",
                            MaxDays = 10,
                            Price = 112.32m,
                            Title = "Fantastic Concrete Gloves"
                        },
                        new
                        {
                            AdId = 79,
                            Description = "Dicta aut dolorem est placeat ratione beatae molestiae. Eos tenetur possimus excepturi esse non et rem. Iure ea dignissimos et et. Autem id est est.",
                            IsGift = false,
                            Location = "Ondrickaburgh",
                            MaxDays = 22,
                            Price = 171.32m,
                            Title = "Incredible Rubber Salad"
                        },
                        new
                        {
                            AdId = 80,
                            Description = "Ipsa dignissimos ea sit fugiat esse voluptatem. Velit asperiores temporibus dolore ut at sint vitae modi. Reprehenderit id voluptatibus aut. Corporis fugit reiciendis quo tempora qui numquam. Harum aliquid aut nemo rerum alias aut architecto sed.",
                            IsGift = false,
                            Location = "North Erickstad",
                            MaxDays = 30,
                            Price = 566.84m,
                            Title = "Handmade Cotton Bacon"
                        },
                        new
                        {
                            AdId = 81,
                            Description = "Vel et voluptates. Doloremque voluptates aspernatur eius at in et. Adipisci qui nesciunt saepe.",
                            IsGift = false,
                            Location = "South Waltonton",
                            MaxDays = 4,
                            Price = 109.60m,
                            Title = "Intelligent Granite Chips"
                        },
                        new
                        {
                            AdId = 82,
                            Description = "Voluptatem unde numquam reprehenderit quam dolores qui voluptatum magni dignissimos. Minima eaque et necessitatibus eius. Voluptatem quibusdam magni rem eum tempore maxime. Quo consequatur delectus enim enim autem harum nisi maiores omnis. Rerum amet quas nihil illo nam accusantium qui.",
                            IsGift = false,
                            Location = "Dimitriside",
                            MaxDays = 6,
                            Price = 219.99m,
                            Title = "Unbranded Rubber Shirt"
                        },
                        new
                        {
                            AdId = 83,
                            Description = "Ducimus quos officiis totam quos culpa corrupti. Quia illum et rerum. Ab consequuntur eius culpa odio facilis explicabo architecto consequatur et.",
                            IsGift = false,
                            Location = "Port Lorenzside",
                            MaxDays = 25,
                            Price = 745.23m,
                            Title = "Fantastic Soft Chips"
                        },
                        new
                        {
                            AdId = 84,
                            Description = "Sed quis quibusdam ipsum eligendi molestiae numquam aut praesentium. Iure odit voluptas aut. Alias enim consequuntur. Dicta deleniti rerum eligendi et rem vero cum.",
                            IsGift = false,
                            Location = "Hobartfort",
                            MaxDays = 3,
                            Price = 75.10m,
                            Title = "Intelligent Wooden Hat"
                        },
                        new
                        {
                            AdId = 85,
                            Description = "Voluptate placeat quisquam debitis adipisci ut. Fugiat saepe nemo voluptatem dolor maxime et. Magnam consequatur nemo eveniet mollitia qui cumque. Magnam natus ducimus quidem dolores enim et dolor consequatur. Culpa ut vel voluptatem. Quis exercitationem aspernatur qui.",
                            IsGift = false,
                            Location = "Kattiefurt",
                            MaxDays = 27,
                            Price = 687.68m,
                            Title = "Handmade Cotton Bacon"
                        },
                        new
                        {
                            AdId = 86,
                            Description = "Et dolore ad impedit repudiandae totam ipsam maxime quo. Occaecati ut consequuntur et sunt neque. Labore incidunt nesciunt sit. Dolores quia sed minima mollitia nobis omnis. Soluta corrupti odit suscipit placeat sapiente corporis adipisci laudantium omnis. Ut culpa rerum ullam est nihil alias ullam cupiditate deserunt.",
                            IsGift = false,
                            Location = "New Madelynnfort",
                            MaxDays = 1,
                            Price = 750.08m,
                            Title = "Tasty Rubber Tuna"
                        },
                        new
                        {
                            AdId = 87,
                            Description = "Maiores fugiat omnis doloremque eos autem ut laborum. Ut est soluta ut voluptatum voluptatem vero voluptatem excepturi. Deserunt eum ut quis totam eveniet qui molestias id. Aliquid id eum cum. Iste placeat eos ut placeat. Aspernatur est nam dolorum odio repudiandae iure aliquid.",
                            IsGift = false,
                            Location = "Trantowside",
                            MaxDays = 3,
                            Price = 778.46m,
                            Title = "Gorgeous Concrete Fish"
                        },
                        new
                        {
                            AdId = 88,
                            Description = "Dolores voluptate quis dolorem in. Commodi earum alias consequatur et enim asperiores. Omnis tempora dolores eligendi sunt nam accusantium maiores et. Quod voluptatem quam non. Qui aut consequatur.",
                            IsGift = false,
                            Location = "South Brentborough",
                            MaxDays = 11,
                            Price = 933.51m,
                            Title = "Gorgeous Wooden Ball"
                        },
                        new
                        {
                            AdId = 89,
                            Description = "Vel molestiae quisquam ut quia ipsam omnis repellendus iste dolor. Quis voluptatem nisi consequuntur nihil beatae dicta quo necessitatibus id. Fugit et dignissimos fuga nihil aut natus ea esse velit. Architecto nobis qui sit quam dolore non.",
                            IsGift = false,
                            Location = "Leopoldoview",
                            MaxDays = 19,
                            Price = 325.32m,
                            Title = "Gorgeous Frozen Chips"
                        },
                        new
                        {
                            AdId = 90,
                            Description = "Non quasi esse id corporis eum ipsam. Blanditiis omnis saepe libero modi voluptatem omnis totam. Architecto distinctio in voluptate distinctio voluptas et reprehenderit asperiores.",
                            IsGift = false,
                            Location = "Jaylenmouth",
                            MaxDays = 6,
                            Price = 639.16m,
                            Title = "Practical Metal Car"
                        },
                        new
                        {
                            AdId = 91,
                            Description = "Asperiores molestiae est ullam velit. Delectus optio voluptatem eum iure. Accusamus at molestias voluptates suscipit.",
                            IsGift = false,
                            Location = "Brakusmouth",
                            MaxDays = 7,
                            Price = 789.28m,
                            Title = "Intelligent Plastic Pizza"
                        },
                        new
                        {
                            AdId = 92,
                            Description = "Ad repudiandae laudantium alias ipsum sapiente esse voluptatum fugiat ullam. Maiores ipsa optio ratione enim. Id ut laborum necessitatibus tempore qui explicabo. Hic quidem fugit sed impedit laudantium blanditiis culpa qui. Dolor vero eum numquam nisi qui vel cum. Aut fugiat inventore vero dicta deleniti expedita.",
                            IsGift = false,
                            Location = "Leonberg",
                            MaxDays = 1,
                            Price = 602.70m,
                            Title = "Intelligent Cotton Keyboard"
                        },
                        new
                        {
                            AdId = 93,
                            Description = "Ullam enim quia quo ut. Officia consequatur commodi blanditiis minus iure. Neque molestias repellat sed sed sit saepe dolor doloremque est.",
                            IsGift = false,
                            Location = "Lake Rosemarieborough",
                            MaxDays = 13,
                            Price = 87.39m,
                            Title = "Generic Granite Chicken"
                        },
                        new
                        {
                            AdId = 94,
                            Description = "Sequi odit iste. Architecto molestiae totam at quisquam accusantium et ipsam quisquam. Sint id et. Magni voluptas perspiciatis ut unde. Beatae illo quae. Et voluptas delectus illo.",
                            IsGift = false,
                            Location = "Port Addie",
                            MaxDays = 13,
                            Price = 442.44m,
                            Title = "Incredible Steel Soap"
                        },
                        new
                        {
                            AdId = 95,
                            Description = "Nemo optio magni dignissimos consequuntur corporis repudiandae deleniti provident ut. Libero deleniti rerum natus corrupti optio sit. Nemo non a inventore accusamus et. Ab fugit neque est quia ut et laborum sapiente.",
                            IsGift = false,
                            Location = "Weberfurt",
                            MaxDays = 28,
                            Price = 742.99m,
                            Title = "Gorgeous Cotton Bike"
                        },
                        new
                        {
                            AdId = 96,
                            Description = "Est iure quia nulla tenetur facilis accusantium. Fugit repellat ut rerum. Occaecati ad magnam et ipsam. Doloremque consequatur omnis et molestiae impedit omnis et sunt. Inventore quos est voluptas ea velit totam molestiae.",
                            IsGift = false,
                            Location = "East Arlo",
                            MaxDays = 6,
                            Price = 327.82m,
                            Title = "Licensed Rubber Soap"
                        },
                        new
                        {
                            AdId = 97,
                            Description = "Aut et quos ducimus quia molestiae cumque et. Occaecati velit dolores in in itaque sunt illo quas fuga. Ut quia consequatur quia non.",
                            IsGift = false,
                            Location = "Lake Rossfurt",
                            MaxDays = 30,
                            Price = 249.67m,
                            Title = "Incredible Granite Salad"
                        },
                        new
                        {
                            AdId = 98,
                            Description = "Ratione est quis ullam fuga vero. Rerum est dolores consequatur. Et possimus id fugit maiores eveniet est. Nulla dolorem sint perferendis cumque at qui asperiores enim. Quidem occaecati dolorum et nihil ducimus dolores quia est ipsa. Eos animi qui.",
                            IsGift = false,
                            Location = "East Lemuel",
                            MaxDays = 28,
                            Price = 235.89m,
                            Title = "Rustic Plastic Soap"
                        },
                        new
                        {
                            AdId = 99,
                            Description = "Deserunt voluptatibus eligendi ex. Est eaque et cum quo et nostrum. Maxime sit quis reiciendis nam quia qui optio maiores similique.",
                            IsGift = false,
                            Location = "Millieport",
                            MaxDays = 8,
                            Price = 896.88m,
                            Title = "Handmade Wooden Towels"
                        },
                        new
                        {
                            AdId = 100,
                            Description = "Qui et dignissimos facere dolor est. Consequatur nulla sit omnis eveniet alias nisi eos deserunt rerum. Distinctio qui vel rem.",
                            IsGift = false,
                            Location = "Hardyville",
                            MaxDays = 20,
                            Price = 120.68m,
                            Title = "Sleek Wooden Shoes"
                        });
                });

            modelBuilder.Entity("EasyRent.Data.Entities.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AdditionalInformation")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("City")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Country")
                        .HasColumnType("character varying(30)")
                        .HasMaxLength(30);

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AddressId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("EasyRent.Data.Entities.BookmarkAd", b =>
                {
                    b.Property<int>("BookmarkAdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AdId")
                        .HasColumnType("integer");

                    b.Property<int>("BookmarkListId")
                        .HasColumnType("integer");

                    b.HasKey("BookmarkAdId");

                    b.HasIndex("AdId");

                    b.HasIndex("BookmarkListId");

                    b.ToTable("BookmarkAds");
                });

            modelBuilder.Entity("EasyRent.Data.Entities.BookmarkList", b =>
                {
                    b.Property<int>("BookmarkListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("BookmarkListId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("BookmarkLists");
                });

            modelBuilder.Entity("EasyRent.Data.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("character varying(30)")
                        .HasMaxLength(30);

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Детские товары"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Техника и электроника"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Хобби и отдых"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Свадьба и праздники"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Автотовары"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Сад и огород"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "Здоровье"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "Спорт, туризм и активный отдых"
                        },
                        new
                        {
                            CategoryId = 9,
                            Name = "Ремонт и стройка"
                        },
                        new
                        {
                            CategoryId = 10,
                            Name = "Другое"
                        });
                });

            modelBuilder.Entity("EasyRent.Data.Entities.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("EasyRent.Data.Entities.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AdId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Url")
                        .HasColumnType("character varying(100)")
                        .HasMaxLength(100);

                    b.HasKey("ImageId");

                    b.HasIndex("AdId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("EasyRent.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("EasyRent.Data.Entities.Subcategory", b =>
                {
                    b.Property<int>("SubcategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(30)")
                        .HasMaxLength(30);

                    b.HasKey("SubcategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Subcategories");

                    b.HasData(
                        new
                        {
                            SubcategoryId = 1,
                            CategoryId = 1,
                            Name = "Мужская одежда"
                        },
                        new
                        {
                            SubcategoryId = 2,
                            CategoryId = 1,
                            Name = "Женская одежда"
                        },
                        new
                        {
                            SubcategoryId = 3,
                            CategoryId = 1,
                            Name = "Обувь"
                        },
                        new
                        {
                            SubcategoryId = 4,
                            CategoryId = 1,
                            Name = "Для мероприятий"
                        },
                        new
                        {
                            SubcategoryId = 5,
                            CategoryId = 1,
                            Name = "Аксессуары"
                        },
                        new
                        {
                            SubcategoryId = 6,
                            CategoryId = 1,
                            Name = "Другое"
                        },
                        new
                        {
                            SubcategoryId = 7,
                            CategoryId = 2,
                            Name = "Одежда"
                        },
                        new
                        {
                            SubcategoryId = 8,
                            CategoryId = 2,
                            Name = "Обувь"
                        },
                        new
                        {
                            SubcategoryId = 9,
                            CategoryId = 2,
                            Name = "Игрушки"
                        },
                        new
                        {
                            SubcategoryId = 10,
                            CategoryId = 2,
                            Name = "Транспорт и коляски"
                        },
                        new
                        {
                            SubcategoryId = 11,
                            CategoryId = 2,
                            Name = "Другое"
                        },
                        new
                        {
                            SubcategoryId = 12,
                            CategoryId = 3,
                            Name = "Бытовая техника"
                        },
                        new
                        {
                            SubcategoryId = 13,
                            CategoryId = 3,
                            Name = "Телефоны, планшеты, гаджеты"
                        },
                        new
                        {
                            SubcategoryId = 14,
                            CategoryId = 3,
                            Name = "Компьютерная техника"
                        },
                        new
                        {
                            SubcategoryId = 15,
                            CategoryId = 3,
                            Name = "Консоли"
                        },
                        new
                        {
                            SubcategoryId = 16,
                            CategoryId = 3,
                            Name = "Другое"
                        },
                        new
                        {
                            SubcategoryId = 17,
                            CategoryId = 3,
                            Name = "Компьютерные игры"
                        },
                        new
                        {
                            SubcategoryId = 18,
                            CategoryId = 3,
                            Name = "Настольные игры"
                        },
                        new
                        {
                            SubcategoryId = 19,
                            CategoryId = 3,
                            Name = "Музыкальные инструменты"
                        },
                        new
                        {
                            SubcategoryId = 20,
                            CategoryId = 3,
                            Name = "Книги и журналы"
                        },
                        new
                        {
                            SubcategoryId = 21,
                            CategoryId = 3,
                            Name = "Охота и рыбалка"
                        },
                        new
                        {
                            SubcategoryId = 22,
                            CategoryId = 3,
                            Name = "Другое"
                        },
                        new
                        {
                            SubcategoryId = 23,
                            CategoryId = 4,
                            Name = "Одежда"
                        },
                        new
                        {
                            SubcategoryId = 24,
                            CategoryId = 4,
                            Name = "Обувь"
                        },
                        new
                        {
                            SubcategoryId = 25,
                            CategoryId = 4,
                            Name = "Аксессуары"
                        },
                        new
                        {
                            SubcategoryId = 26,
                            CategoryId = 4,
                            Name = "Мебель"
                        },
                        new
                        {
                            SubcategoryId = 27,
                            CategoryId = 4,
                            Name = "Другое"
                        },
                        new
                        {
                            SubcategoryId = 28,
                            CategoryId = 5,
                            Name = "Автомобили"
                        },
                        new
                        {
                            SubcategoryId = 29,
                            CategoryId = 5,
                            Name = "Мотоциклы, квадроциклы"
                        },
                        new
                        {
                            SubcategoryId = 30,
                            CategoryId = 5,
                            Name = "Аксессуары"
                        },
                        new
                        {
                            SubcategoryId = 31,
                            CategoryId = 5,
                            Name = "Инструмент"
                        },
                        new
                        {
                            SubcategoryId = 32,
                            CategoryId = 5,
                            Name = "Другое"
                        },
                        new
                        {
                            SubcategoryId = 33,
                            CategoryId = 6,
                            Name = "Инструмент"
                        },
                        new
                        {
                            SubcategoryId = 34,
                            CategoryId = 6,
                            Name = "Другое"
                        },
                        new
                        {
                            SubcategoryId = 35,
                            CategoryId = 7,
                            Name = "Тренажеры"
                        },
                        new
                        {
                            SubcategoryId = 36,
                            CategoryId = 7,
                            Name = "Другое"
                        },
                        new
                        {
                            SubcategoryId = 37,
                            CategoryId = 8,
                            Name = "Зимние спорттовары"
                        },
                        new
                        {
                            SubcategoryId = 38,
                            CategoryId = 8,
                            Name = "Летние спорттовары"
                        },
                        new
                        {
                            SubcategoryId = 39,
                            CategoryId = 8,
                            Name = "Всесезонные спорттовары"
                        },
                        new
                        {
                            SubcategoryId = 40,
                            CategoryId = 8,
                            Name = "Туристические товары"
                        },
                        new
                        {
                            SubcategoryId = 41,
                            CategoryId = 8,
                            Name = "Велотовары"
                        },
                        new
                        {
                            SubcategoryId = 42,
                            CategoryId = 8,
                            Name = "Туристические услуги"
                        },
                        new
                        {
                            SubcategoryId = 43,
                            CategoryId = 8,
                            Name = "Другое"
                        },
                        new
                        {
                            SubcategoryId = 44,
                            CategoryId = 9,
                            Name = "Инструмент"
                        },
                        new
                        {
                            SubcategoryId = 45,
                            CategoryId = 9,
                            Name = "Другое"
                        });
                });

            modelBuilder.Entity("EasyRent.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<int?>("AddressId")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<string>("LastName")
                        .HasColumnType("character varying(40)")
                        .HasMaxLength(40);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("EasyRent.Data.Entities.UserAd", b =>
                {
                    b.Property<int>("UserAdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AdId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserAdId");

                    b.HasIndex("AdId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAds");
                });

            modelBuilder.Entity("EasyRent.Data.Entities.UserContact", b =>
                {
                    b.Property<int>("UserContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ContactId")
                        .HasColumnType("integer");

                    b.Property<string>("ContactValue")
                        .HasColumnType("character varying(50)")
                        .HasMaxLength(50);

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserContactId");

                    b.HasIndex("ContactId");

                    b.HasIndex("UserId");

                    b.ToTable("UserContacts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("EasyRent.Data.Entities.Address", b =>
                {
                    b.HasOne("EasyRent.Data.Entities.User", "User")
                        .WithOne("Address")
                        .HasForeignKey("EasyRent.Data.Entities.Address", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EasyRent.Data.Entities.BookmarkAd", b =>
                {
                    b.HasOne("EasyRent.Data.Entities.Ad", "Ad")
                        .WithMany()
                        .HasForeignKey("AdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyRent.Data.Entities.BookmarkList", "BookmarkList")
                        .WithMany("BookmarkAds")
                        .HasForeignKey("BookmarkListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EasyRent.Data.Entities.BookmarkList", b =>
                {
                    b.HasOne("EasyRent.Data.Entities.User", "User")
                        .WithOne("BookmarkList")
                        .HasForeignKey("EasyRent.Data.Entities.BookmarkList", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EasyRent.Data.Entities.Image", b =>
                {
                    b.HasOne("EasyRent.Data.Entities.Ad", "Ad")
                        .WithMany("Images")
                        .HasForeignKey("AdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EasyRent.Data.Entities.Subcategory", b =>
                {
                    b.HasOne("EasyRent.Data.Entities.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EasyRent.Data.Entities.UserAd", b =>
                {
                    b.HasOne("EasyRent.Data.Entities.Ad", "Ad")
                        .WithMany("UserAds")
                        .HasForeignKey("AdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyRent.Data.Entities.User", "User")
                        .WithMany("UserAds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EasyRent.Data.Entities.UserContact", b =>
                {
                    b.HasOne("EasyRent.Data.Entities.Contact", "Contact")
                        .WithMany("UserContacts")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyRent.Data.Entities.User", "User")
                        .WithMany("UserContacts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("EasyRent.Data.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("EasyRent.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("EasyRent.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("EasyRent.Data.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyRent.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("EasyRent.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
